package d.pochernin.fishplaces.entity;
// Generated May 28, 2016 8:22:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FishInPlace generated by hbm2java
 */
@Entity
@Table(name = "fish_in_places", catalog = "fish_places"
)
public class FishInPlace implements java.io.Serializable {

    private int id;
    private Fish fishes;
    private Place places;

    public FishInPlace() {
    }

    public FishInPlace(int id) {
        this.id = id;
    }

    public FishInPlace(int id, Fish fishes, Place places) {
        this.id = id;
        this.fishes = fishes;
        this.places = places;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fish_id")
    public Fish getFishes() {
        return this.fishes;
    }

    public void setFishes(Fish fishes) {
        this.fishes = fishes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "place_id")
    public Place getPlaces() {
        return this.places;
    }

    public void setPlaces(Place places) {
        this.places = places;
    }

}
