package d.pochernin.fishplaces.entity;
// Generated May 28, 2016 8:22:08 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Place generated by hbm2java
 */
@Entity
@Table(name = "places", catalog = "fish_places"
)
public class Place implements java.io.Serializable {

    private Integer placeId;
    private String placeName;
    private float placeGeoLat;
    private float placeGeoLong;
    private Set fishInPlaceses = new HashSet(0);

    public Place() {
    }

    public Place(long placeGeoLat, long placeGeoLong) {
        this.placeGeoLat = placeGeoLat;
        this.placeGeoLong = placeGeoLong;
    }

    public Place(String placeName, long placeGeoLat, long placeGeoLong, Set fishInPlaceses) {
        this.placeName = placeName;
        this.placeGeoLat = placeGeoLat;
        this.placeGeoLong = placeGeoLong;
        this.fishInPlaceses = fishInPlaceses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "place_id", unique = true, nullable = false)
    public Integer getPlaceId() {
        return this.placeId;
    }

    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    @Column(name = "place_name")
    public String getPlaceName() {
        return this.placeName;
    }

    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

    @Column(name = "place_geo_lat", nullable = false, precision = 255)
    public float getPlaceGeoLat() {
        return this.placeGeoLat;
    }

    public void setPlaceGeoLat(float placeGeoLat) {
        this.placeGeoLat = placeGeoLat;
    }

    @Column(name = "place_geo_long", nullable = false, precision = 255)
    public float getPlaceGeoLong() {
        return this.placeGeoLong;
    }

    public void setPlaceGeoLong(float placeGeoLong) {
        this.placeGeoLong = placeGeoLong;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "places")
    public Set<FishInPlace> getFishInPlaceses() {
        return this.fishInPlaceses;
    }

    public void setFishInPlaceses(Set<FishInPlace> fishInPlaceses) {
        this.fishInPlaceses = fishInPlaceses;
    }

}
