package ua.com.codefire.dao.entity;
// Generated May 28, 2016 8:22:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;
import ua.com.codefire.dao.FishDAOImpl;
import ua.com.codefire.dao.PlacesDAOImpl;

/**
 * FishInPlace generated by hbm2java
 */
@NamedQueries({
    @NamedQuery(name = "FishInPlaces.findByPlaceId", query = "SELECT f FROM FishInPlace f WHERE f.places = :placeId"),
    @NamedQuery(name = "FishInPlaces.findByFishId", query = "SELECT f FROM FishInPlace f WHERE f.fishes = :fishId")
})

@Entity
@Table(name = "fish_in_places")

public class FishInPlace implements java.io.Serializable {

    private int id;
    private int fishes;
    private int places;
    private FishDAOImpl fish;
    private PlacesDAOImpl place;

    public FishInPlace() {
    }

    public FishInPlace(int id) {
        this.id = id;
    }

    public FishInPlace(Fish fishes, Place places) {
        this.fishes = fishes.getFishId();
        this.places = places.getPlaceId();
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fish_id")
    public Fish getFishes() {
        return fish.getById(this.id);
    }

    public void setFishes(Fish fishes) {
        this.fishes = fishes.getFishId();
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "place_id")
    public Place getPlaces() {
        return place.getById(this.id);
    }

    public void setPlaces(Place places) {
        this.places = places.getPlaceId();
    }

}
